# Generated by Django 5.2.4 on 2025-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotp_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hotp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
